update postinst

diff --git a/postinst b/postinst
--- a/postinst
+++ b/postinst
@@ -1,5 +1,46 @@
 #!/bin/sh
+# see: dh_installdeb(1)
 
-chown -R www-data:www-data /opt/portfolio
-find /opt/portfolio -type d -exec chmod 755 "{}" \;
-find /opt/portfolio -type f -exec chmod 644 "{}" \;
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+case "$1" in
+
+  configure)
+    chown -R www-data:www-data /opt/portfolio
+    find /opt/portfolio -type d -exec chmod 755 "{}" \;
+    find /opt/portfolio -type f -exec chmod 644 "{}" \;
+    exit 0
+  ;;
+
+  abort-upgrade)
+    exit 0
+  ;;
+
+  abort-remove)
+    exit 0
+  ;;
+
+  abort-deconfigure)
+    exit 0
+  ;;
+
+  *)
+    echo "postinst called with unknown argument \`$1'" >&2
+    exit 1
+  ;;
+
+esac
+
+exit 0
